### ISSUE TITLE
Support javascript outputs

### ISSUE THREAD

**Issue by echarles** [datalayer/support#3]
Snippets doesn't allow showing panel because Javascript is disabled

Reported on https://datalayer.io/public/snippet/3483f345-cbb3-4ab6-8dd3-3cb04dfcd2e9

**Comment by echarles** [comment]
cc/ @hyamanieu

**Comment by echarles** [comment]
This is working now by default with the [jupyterlab javascript renderer](https://github.com/jupyterlab/jupyterlab/tree/master/packages/javascript-extension). This needs also to be added to the notebook and a fix will be deployed tomorrow.

<img width="861" alt="Screenshot 2022-07-06 at 19 04 49" src="https://user-images.githubusercontent.com/226720/177605440-a4833e0d-a1f3-4b90-b64f-e4449da98a86.png">

**Comment by hyamanieu** [comment]
> For now the javascript render will be enabled by default. We can discuss how secure this is and which trust mecanism should be added to avoid a user being impact by unfriendly javascript code execution

If snippets are meant to be available on the larger web, you could use a switch which by default is off, and triggers a warning if someone wants to turn it on.

For notebooks I would say it's not necessary.
